### PR TITLE
Comparator to flag invalid primary tag combinations

### PR DESCRIPTION
**Pull request by bkowshik**
## Objective
- Fixes: https://github.com/mapbox/osm-compare/issues/94

Per https://github.com/mapbox/osm-compare/issues/94#issuecomment-283905597
> Amazing stats @bkowshik, this directly gives the probability of any tag combination on OSM. With these 286 invalid and 330 possibly erroneous tag combination, can we already start flagging them?

- Happy about how we parse a csv file instead of a json, making it easy on the 👀 

## Next actions
- [ ] Would love to get some 👀 @amishas157 
- [ ] Merge to `master`

---

cc: @planemad @geohacker

### CODE REVIEW

**Comment by geohacker** [comment]
@bkowshik this uses a csv file for the tag combination scores - how do you plan to make this maintainable? should we use the taginfo API directly?

**Comment by bkowshik** [comment]
At the moment, we have a script to generate the csv file here:

- https://github.com/mapbox/osm-compare/blob/master/scripts/primary-map-features.js

## Options

@geohacker, I could think of the following 3 options:

1. `csv` file in the repository
    - TagInfo is not queried for each feature
    - Simple to build and easy to understand
    - Needs to be updated manually using the script ^
2. `csv` file created during deploy
    - TagInfo is not queried for each feature
    - Latest data is queried from TagInfo during deploy
    - Data is as frequent as the number of deploys
    - Makes the deploy a little slower
3. Query TagInfo
    - TagInfo is queried for each feature which is a lot of features!!!
    - We have the latest data and no manual maintenance

Unless you are seeing something here, I am happy with the current setup, (option `1`). We will get a better sense of what is needed once we deploy and :eyes: the results for a few days.

**Comment by planemad** [comment]
👍 the current CSV is good till we see some results from this. We can think about scaling with taginfo if this works as expected.

**Comment by amishas157** [comment]
@bkowshik This looks good to go. And also regarding keeping the tag info data updated, i think manually running scripts is fine. As there should not be much difference in tag-info data on daily basis, if we think of it in terms of percentage. But as we are [scaling our comparators](https://github.com/mapbox/osm-compare/issues/96) based on taginfo, we can put some cron jobs to run these scripts on a monthly basis.

**Comment by bkowshik** [comment]
Published to npm as version: `4.14.0`

**Comment by geohacker** [comment]
🎉

**Pull request merged**
