### PR TITLE
Understanding harmful edits to water bodies on OSM

### PR DESCRIPTION
**Pull request by bkowshik**
- *NOTE: This is a work in progress*
- The analysis and findings are in the Jupyter notebook: `notebooks/Save water.ipynb`.

---

cc: @planemad @geohacker @manoharuss

### CODE REVIEW

**Comment by bkowshik** [comment]
I am hoping we could take learning's from here to write a better comparator for: https://github.com/mapbox/osm-compare/issues/108

**Comment by bkowshik** [comment]
When I looked into the errors with the number of nodes in the feature geometry, etc had a wired issue with `osm-qa-tiles`. Basically, there were duplicate features with different geometries but same properties. This causes problems as the smaller part of the lake is flagged as a lake with low number of nodes. Ex: [way/334804714](http://www.openstreetmap.org/way/334804714):

screen shot 2017-03-23 at 8 24 24 am

```json
# Feature 1
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-114.87328332848847,50.1789112157208],[-114.8731864336878,50.17887272924324],[-114.87306238152087,50.17884422668544],[-114.873046875,50.17882710367178],[-114.873046875,50.17870944317349],[-114.87305450253189,50.178700425386126],[-114.87316682003438,50.178683302320906],[-114.87329380586743,50.178686200896635],[-114.87342012114823,50.17864342004802],[-114.87347586080432,50.17868051109966],[-114.87345918081701,50.17873461782091],[-114.87350922077894,50.17887841901731],[-114.87340696156025,50.17893112991112],[-114.87328332848847,50.1789112157208]]]},"properties":{"@id":334804714,"@type":"way","@version":1,"@changeset":29744389,"@uid":1752660,"@user":"Barry McLane","@timestamp":1427351350,"water":"lake","source":"Freshwater Atlas","natural":"water"}}

# Feature 2
{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-114.87299541011453,50.17877020583927],[-114.873046875,50.17870944317349],[-114.873046875,50.17882710367178],[-114.87299541011453,50.17877020583927]]]},"properties":{"@id":334804714,"@type":"way","@version":1,"@changeset":29744389,"@uid":1752660,"@user":"Barry McLane","@timestamp":1427351350,"water":"lake","source":"Freshwater Atlas","natural":"water"}}
```

*NOTE: Both features ^ have same properties including the ID, but different geometries*

**Comment by bkowshik** [comment]
Curious if this issue was with just `osm-qa-tiles`, I looked into filtering new lakes from `pbf` files using the latest file here: https://planet.openstreetmap.org/pbf/

Used the handy [`osmlazer`](https://github.com/geohacker/osmlazer/), thanks to @geohacker to filter out lakes with version 1. The results looked good when tested on a smaller scale for Bengaluru, there are 8 new lakes with version `1`.

screen shot 2017-03-24 at 11 45 57 am

But, things when scaled to the US are failing which [I am trying to understand](https://github.com/geohacker/osmlazer/issues/4).

## Next actions
- [ ] Extract a clean dataset of version `1` lakes in the US
- [ ] Run scripts in the Jupyter notebook on ^

**Comment by bkowshik** [comment]
The csv file with features for version 1 lakes in the US is below:
- Gist: https://gist.github.com/bkowshik/6e0fc433ecbe82e8ea2816ee5e4b198c

---

I ran the Jupter notebook on ^ dataset and there were some interesting findings. @planemad @manoharuss can we do a manual review of the features in the Google sheet below with around 50 features:

- Google sheet: [Save water - Validation - Mapbox](https://docs.google.com/spreadsheets/d/1ysBlNKE5VnxEEFmYCLmUvlHtEzX2_464rbOcU_ZGFOo/edit?usp=sharing)

---

## Interesting outliers

- http://www.openstreetmap.org/way/379854480

screen shot 2017-03-28 at 11 05 22 pm

*Lake with area zero rendered as a LineString instead of a Polygon*

- http://www.openstreetmap.org/way/292023847

screen shot 2017-03-28 at 11 09 00 pm

*Lake with suspiciously few coordinates*

- http://www.openstreetmap.org/relation/6376044

screen shot 2017-03-28 at 11 22 28 pm

*Version 1 lake with the most number of feature coordinates*

- http://www.openstreetmap.org/way/469257767

screen shot 2017-03-28 at 11 33 09 pm

*Feature covers close to 100% of feature bbox*

**Comment by planemad** [comment]
@Fa7C0n @nikhilprabhakar lets inspect the [list of unusual water bodies](https://docs.google.com/spreadsheets/d/1ysBlNKE5VnxEEFmYCLmUvlHtEzX2_464rbOcU_ZGFOo/edit#gid=560091885) that @bkowshik has generated and check which of them are valid or invalid. This will help better understand which of the heurestics has a better probability of describing an invalid water body.

**Comment by nikhilprabhakar** [comment]
@fa7c0n and I went through the [spreadsheet](https://docs.google.com/spreadsheets/d/1ysBlNKE5VnxEEFmYCLmUvlHtEzX2_464rbOcU_ZGFOo/edit#gid=560091885) to review the the list of unusual water bodies that was generated by @bkowshik. Below are the detection rate of the comparators:

#### Comparators that Could be harmful

| Type of Comparator | Detection % |
| ------------------ | ----------- |
| Area of lake is zero | 100% |
| Lake with geometry type node| 90% | 
| Lake with low coordinates | 70% |
| Feature covers 100% of feature BBOX | 70% |
| Lakes with small names | 40% |
| Features flagged as outliers by ML | 0% |

#### Comparators that Should not be harmful

| Type of Comparator | Detection % |
| ------------------ | ----------- |
| Lakes with high coordinates | 100% |
| Lakes with large names | 90% |







#### Findings:


- `Lakes with small names` produced a lot of false positives but also helped in identifying the lakes with bad geometry. we can use this detector to increase other detectors precision but not as a standalone detector.

- `lake with low coordinates` detector helped in identifying the roughly traced water bodies which are not depicting the real scenario and this also helped in finding the harmful edits in residential areas 👉 [Detected Scenario](https://www.openstreetmap.org/#map=19/31.552652808115727/-84.72029034075771)

- Some of the detections under `Lake with low coordinates` were able to point out lakes in the middle of a city / residential area where there was no lakes actually present 👉 [Detected Scenario](https://www.openstreetmap.org/#map=19/30.227054066172368/-95.46150636315618)

- `Lake with low coordinates` were able to detect a case where the user named the feature after the user's name. So adding a detector to detect this kind of edits will help to find a lot of harmful edits in the future 👉 [Detected Scenario](https://www.openstreetmap.org/#map=20/40.31740042416518/-74.79454251432915)

- The `ML detector` has produced 100% false positives. But this detector can be used in combination with other detectors to produce more accurate results.

- `Feature covers 100% of feature BBOX` will be really useful to detect most the harmful edits in residential areas.  This will help in identifying scenario's like pokemon edits which are coming to our pipeline.

cc:// @planemad

**Comment by bkowshik** [comment]
Thank you @nikhilprabhakar and @Fa7C0n for the detailed review. This is super helpful!

## Next actions
- [ ] Analyze if combining two categories improves the accuracy of detection.
    - Ex: What does a feature with small name and less number of co-ordinates look like?
- [ ] Run for all lakes in the US
    - In the last run, we worked only with lakes with `version=1`

---

We should have the new `csv` towards the end of this week. 😃 

---

cc: @planemad

**Comment by amishas157** [comment]
Hey @bkowshik 👋  , just wanted to check what are our next actions on this?

**Comment by bkowshik** [comment]
@amishas157 No next actions here. I think this is useful reference to keep. Should we merge?

**Comment by amishas157** [comment]
@bkowshik sounds good, let's rebase and merge?

**Pull request merged**
