### PR TITLE
added invalid-tag-combination compare function with fixtures

### PR DESCRIPTION
**Pull request by manoharuss**
Added a starting set of pairs of invalid feature tag combinations.

screenshot 2016-12-17 17 58 42

- We can keep adding pairs of invalid/implausible tag combinations to this list as we see fit and also change the structure of the matrix in future as we move forward.

cc @planemad @maning @krishnanammala @chtnha @batpad @geohacker

### CODE REVIEW

**Comment by geohacker** [comment]
Looks good to me @manoharuss! I'm not sure if we want to list impossible combinations or look through a set of possible combinations. But this looks like a great start!

**Comment by geohacker** [comment]
@manoharuss should we prioritise this one? I'm still not sure whether we maintain a canonical possible combinations list or otherwise.

**Comment by bkowshik** [comment]
With the PR, https://github.com/mapbox/osm-compare/pull/121 @amishas157 adds common values for all 26 primary tags on OSM. Are we good to close this in favor of https://github.com/mapbox/osm-compare/pull/121

**Comment by manoharuss** [comment]
@bkowshik Yes. this is good to close. Work on https://github.com/mapbox/osm-compare/pull/121 is a better approach. closing.

**Pull request closed without merging**
